# Link the MSVC C runtime into the binary. A fresh Windows install has no
# VCRUNTIME140.dll unless the VC++ Redistributable was installed.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
